site_name: MDRM êµìœ¡ ì»¤ë¦¬í˜ëŸ¼

site_author: MDRM Team
site_url: https://ai-uzoogom.github.io/MDRM_manual/

theme:
  name: material
  language: ko
  palette:
    scheme: default
    primary: blue
    accent: blue
  font:
    text: Pretendard
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.tabs.link

nav:
  - ğŸ : index.md
  - DAY 1:
    - í•™ìŠµ ì•ˆë‚´: day1/index.md
    - ì†”ë£¨ì…˜ ê°œìš”: day1/MDRM_ì†”ë£¨ì…˜_ê°œìš”.md
    - ì¸í”„ë¼:
      - â–¸ ë””ìŠ¤í¬ êµ¬ì„±: day1/ì¸í”„ë¼_ë””ìŠ¤í¬_êµ¬ì„±.md
      - â–¸ OS íŠœë‹: day1/ì¸í”„ë¼_OS_íŠœë‹.md
      - â–¸ í¬íŠ¸ ì •ë³´: day1/ì¸í”„ë¼_í¬íŠ¸_ì •ë³´.md
    - Docker:
      - â–¸ Docker ì„¤ì¹˜: day1/Docker_ì„¤ì¹˜_ê°€ì´ë“œ.md
      - â–¸ Docker í™˜ê²½ ì„¤ì •: day1/Docker_í™˜ê²½_ì„¤ì •.md
    - Podman:
      - â–¸ Podman ì„¤ì¹˜: day1/Podman_ì„¤ì¹˜_ê°€ì´ë“œ.md
      - â–¸ Podman í™˜ê²½ ì„¤ì •: day1/Podman_í™˜ê²½_ì„¤ì •.md
    - MDRM:
      - â–¸ ì„¤ì¹˜ ë° í™•ì¸: day1/MDRM_ì„¤ì¹˜_ë°_í™•ì¸.md
      - â–¸ ì •ì§€ ë° ì¢…ë£Œ: day1/MDRM_ì •ì§€_ë°_ì¢…ë£Œ.md
      - â–¸ ì‹œìŠ¤í…œ ê´€ë¦¬: day1/MDRM_ì‹œìŠ¤í…œ_ê´€ë¦¬.md
  - DAY 2:
    - ê°œìš”: day2/index.md
    - ì—ì´ì „íŠ¸:
        - â–¸ ì„¤ì¹˜ ë° ë“±ë¡: day2/MDRM_Agent_ì„¤ì¹˜_ë°_ë“±ë¡.md
        - â–¸ ìë™ì„¤ì¹˜: day2/MDRM_Agent_ìë™ì„¤ì¹˜.md
        - â–¸ ìˆ˜ë™ì„¤ì¹˜: day2/MDRM_Agent_ìˆ˜ë™ì„¤ì¹˜.md
        - â–¸ ì‹œìŠ¤í…œ ìˆ˜ë™ë“±ë¡: day2/MDRM_Agent_ì‹œìŠ¤í…œìˆ˜ë™ë“±ë¡.md
        - â–¸ Agentless: day2/MDRM_Agent_Agentless.md
        - â–¸ í™˜ê²½ ì„¤ì •: day2/MDRM_Agent_í™˜ê²½_ì„¤ì •.md
    - ëŒ€ì‹œë³´ë“œ:
        - â–¸ ê°œìš”: day2/MDRM_ë©”ë‰´_ëŒ€ì‹œë³´ë“œ.md
        - â–¸ ëŒ€ì‹œë³´ë“œ ê´€ë¦¬: day2/MDRM_ëŒ€ì‹œë³´ë“œ_ê´€ë¦¬.md
        - â–¸ ìœ„ì ¯ í™œìš© ê°€ì´ë“œ: day2/MDRM_ëŒ€ì‹œë³´ë“œ_ìœ„ì ¯.md
    - ì‹œìŠ¤í…œ:
        - â–¸ ê°œìš”: day2/MDRM_ë©”ë‰´_ì‹œìŠ¤í…œ.md
        - â–¸ êµ¬ì„± ë° ê·¸ë£¹ ê´€ë¦¬: day2/MDRM_ì‹œìŠ¤í…œ_êµ¬ì„±_ê´€ë¦¬.md
        - â–¸ ì‹œìŠ¤í…œ ë“±ë¡ ë° ì¶”ê°€: day2/MDRM_ì‹œìŠ¤í…œ_ë“±ë¡_ì¶”ê°€.md
        - â–¸ ëª¨ë‹ˆí„°ë§ ë° ì•Œë¦¼: day2/MDRM_ì‹œìŠ¤í…œ_ëª¨ë‹ˆí„°ë§_ì•Œë¦¼.md
        - â–¸ í”„ë¡œê·¸ë¨ ë°°í¬ ë° ì‘ì—…: day2/MDRM_ì‹œìŠ¤í…œ_ë°°í¬_ì‘ì—….md
        - â–¸ ê³„ì • ê´€ë¦¬: day2/MDRM_ì‹œìŠ¤í…œ_ê³„ì •_ê´€ë¦¬.md
    - ì›Œí¬í”Œë¡œìš°:
        - â–¸ ê°œìš”: day2/MDRM_ë©”ë‰´_ì›Œí¬í”Œë¡œìš°.md
        - â–¸ ë°ì´í„°ì„¼í„° ë° ê·¸ë£¹ ê´€ë¦¬: day2/MDRM_ì›Œí¬í”Œë¡œìš°_êµ¬ì„±_ê´€ë¦¬.md
        - â–¸ í”„ë¡œì„¸ìŠ¤ ì„¤ê³„ ë° ì»´í¬ë„ŒíŠ¸: day2/MDRM_ì›Œí¬í”Œë¡œìš°_ì„¤ê³„_ì»´í¬ë„ŒíŠ¸.md
        - â–¸ ë³€ìˆ˜ í™œìš© ë° ì¡°ê±´ ë¶„ê¸°: day2/MDRM_ì›Œí¬í”Œë¡œìš°_ë³€ìˆ˜_ë¶„ê¸°.md
        - â–¸ ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ë° ëª¨ë‹ˆí„°ë§: day2/MDRM_ì›Œí¬í”Œë¡œìš°_ì‹¤í–‰_ëª¨ë‹ˆí„°ë§.md
        - â–¸ ê´€ë¦¬ ë° ì‹¤í–‰ ë¦¬í¬íŠ¸: day2/MDRM_ì›Œí¬í”Œë¡œìš°_ê´€ë¦¬_ë¦¬í¬íŠ¸.md
    - ì ê²€ì‘ì—…: day2/MDRM_ë©”ë‰´_ì ê²€ì‘ì—….md
    - ì»´í¬ë„ŒíŠ¸: day2/MDRM_ì»´í¬ë„ŒíŠ¸_ê´€ë¦¬.md
    - ì»´í¬ë„ŒíŠ¸ ì‹¤í–‰ í”„ë¡œì„¸ìŠ¤: day2/MDRM_ì»´í¬ë„ŒíŠ¸_ì‹¤í–‰_í”„ë¡œì„¸ìŠ¤.md


plugins:
  - search:
      lang: ko
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: "&copy; 2026 MDRM êµìœ¡ ìë£Œ by ì„œë¹„ìŠ¤ì‚¬ì—…ë³¸ë¶€ 1íŒ€ ê¹€ì¬ì² . All rights reserved."
